[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/home/octobot/supervisord.pid

[program:sshd]
user=root
directory=/
command=/usr/sbin/sshd -D -e
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
startretries=9999
stopwaitsecs=15
autostart=true
autorestart=true

[program:openclaw-gw]
user=octobot
environment=USER="octobot",HOME="/home/octobot",TERM="xterm"
directory=/home/octobot/Openclaw
command=/bin/bash --login -c "/home/octobot/bin/openclaw-gw.sh"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=15
startretries=9999
stopwaitsecs=15
autostart=true
autorestart=true
exitcodes=0,1

[program:claude-remote]
user=octobot
environment=USER="octobot",HOME="/home/octobot",TERM="xterm"
directory=/home/octobot/ClaudeCode
command=/bin/bash --login -c "/home/octobot/bin/claude-remote.exp"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=15
startretries=9999
stopwaitsecs=15
autostart=true
autorestart=true
exitcodes=0,1

[program:paperclip]
user=octobot
environment=USER="octobot",HOME="/home/octobot",TERM="xterm"
directory=/home/octobot/Paperclip
command=/bin/bash --login -c "/home/octobot/bin/paperclip-run.sh"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=15
startretries=9999
stopwaitsecs=15
autostart=true
autorestart=true

[program:hermes-dashboard]
user=octobot
environment=USER="octobot",HOME="/home/octobot",TERM="xterm"
directory=/home/octobot/Hermes
command=/bin/bash --login -c "/home/octobot/bin/hermes-dashboard.sh"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=15
startretries=9999
stopwaitsecs=15
autostart=true
autorestart=true
exitcodes=0,1

[program:obsidian-sync]
user=octobot
environment=USER="octobot",HOME="/home/octobot",TERM="xterm"
directory=/home/octobot/Obsidian
command=/bin/bash --login -c "/home/octobot/bin/obsidian-sync.sh"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
startsecs=15
startretries=9999
stopwaitsecs=15
autostart=true
autorestart=true
exitcodes=0,1